In [1]:
from __future__ import print_function
import torch

In [2]:
x1 = torch.empty(3,6)
print(x1)

tensor([[1.0359e+21, 8.4779e-43, 1.2413e+19, 8.4779e-43, 1.0495e+21, 8.4779e-43],
        [2.9874e+16, 8.4779e-43, 1.0440e+21, 8.4779e-43, 1.2428e+19, 8.4779e-43],
        [1.0495e+21, 8.4779e-43, 1.2446e+19, 8.4779e-43, 1.0487e+21, 8.4779e-43]])


In [3]:
x2 = torch.rand(5,4)
print(x2)

tensor([[0.6131, 0.8714, 0.5240, 0.3953],
        [0.3289, 0.8324, 0.3103, 0.1972],
        [0.5170, 0.1499, 0.9628, 0.8088],
        [0.3624, 0.2299, 0.5223, 0.0421],
        [0.6654, 0.5895, 0.5356, 0.9107]])


In [4]:
x3 = torch.zeros(2,4, dtype=torch.long)
print(x3)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])


In [5]:
x4 = torch.tensor([[0.23, 0.45], [1.28, -3.49]])
print(x4)

tensor([[ 0.2300,  0.4500],
        [ 1.2800, -3.4900]])


In [6]:
x2 = x2.new_ones(3,3, dtype=torch.double)
print(x2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x2 = torch.randn_like(x2, dtype=torch.float16)
print(x2)

tensor([[ 1.0439, -2.2090, -0.8540],
        [-0.6792, -1.3887, -0.1292],
        [-0.8242,  0.7251, -0.2113]], dtype=torch.float16)


In [8]:
x = x2
y = torch.rand(3, 3, dtype=torch.float16)
print(x + y)
print('\n')
print(torch.add(x, y))

tensor([[ 1.4043, -1.9014, -0.6963],
        [-0.5938, -0.6030,  0.7598],
        [-0.6177,  1.5498,  0.5942]], dtype=torch.float16)


tensor([[ 1.4043, -1.9014, -0.6963],
        [-0.5938, -0.6030,  0.7598],
        [-0.6177,  1.5498,  0.5942]], dtype=torch.float16)


In [9]:
res1 = torch.empty(3, 3, dtype=torch.float16)
torch.mul(x, y, out=res1)
print(res1)

tensor([[ 0.3757, -0.6797, -0.1346],
        [-0.0580, -1.0908, -0.1148],
        [-0.1703,  0.5981, -0.1703]], dtype=torch.float16)


In [10]:
y2 = torch.rand(3,3)
print(y2)
print('\n')
y2.add_(res1)
print(y2)

tensor([[0.6858, 0.7354, 0.9298],
        [0.8657, 0.5451, 0.4318],
        [0.7173, 0.4332, 0.1855]])


tensor([[ 1.0615,  0.0557,  0.7951],
        [ 0.8076, -0.5457,  0.3170],
        [ 0.5470,  1.0313,  0.0152]])


In [11]:
print(x3[1,:])

tensor([0, 0, 0, 0])


In [12]:
m = torch.randn(4,4)
n = m.view(16)
p = m.view(-1, 8)
print(m)
print(n)
print(p)

tensor([[-1.5971, -0.6118,  0.2971,  0.0373],
        [-0.4902,  0.8217, -0.1105,  0.0570],
        [ 0.4399, -1.2609, -0.3235,  1.6398],
        [-1.0535, -0.6585,  0.3237,  0.7504]])
tensor([-1.5971, -0.6118,  0.2971,  0.0373, -0.4902,  0.8217, -0.1105,  0.0570,
         0.4399, -1.2609, -0.3235,  1.6398, -1.0535, -0.6585,  0.3237,  0.7504])
tensor([[-1.5971, -0.6118,  0.2971,  0.0373, -0.4902,  0.8217, -0.1105,  0.0570],
        [ 0.4399, -1.2609, -0.3235,  1.6398, -1.0535, -0.6585,  0.3237,  0.7504]])


In [13]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [14]:
a.add_(2)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [15]:
import numpy as np
a1 = np.ones(8)
b1 = torch.from_numpy(a1)
np.add(a1, 3, out=a1)
print(a1)

[4. 4. 4. 4. 4. 4. 4. 4.]


In [16]:
x5 = torch.ones(2, 2, requires_grad=True)
x5

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [17]:
y3 = x5 + 2
print(y3)
print('\n')
print(y3.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)




In [18]:
z1 = y3 * y3 * 3
out = z1.mean()

print(z1, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [19]:
a1 = torch.randn(2,2)
a1 = ((a1 * 3) / (a1 - 1))
print(a1.requires_grad)
a1.requires_grad_(True)
print(a1.requires_grad)

False
True


In [20]:
b1 = (a1 * a1).sum()
print(b1.grad_fn)

In [21]:
out.backward(retain_graph=True)
print(x5.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [29]:
x6 = torch.randn(3, requires_grad=True)
y4 = x6 * 2

while y4.data.norm() < 1000:
    y4 = y4 * 2

print(y4)

tensor([ 283.8253,  999.8781, 1100.4633], grad_fn=<MulBackward0>)


In [30]:
v1 = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y4.backward(v1, retain_graph=True)
print(x6.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [32]:
print(x6.requires_grad)
print((x6 ** 2).requires_grad)

with torch.no_grad():
    print((x6 ** 2).requires_grad)

True
True
False


In [33]:
print(x6.requires_grad)
y5 = x6.detach()
print(y5.requires_grad)
print(x6.eq(y5).all())

True
False
tensor(True)
