In [16]:
from __future__ import print_function
import torch

In [17]:
x1 = torch.empty(3,6)
print(x1)

tensor([[1.0102e-38, 1.0286e-38, 1.0194e-38, 9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38, 9.5510e-39, 1.0561e-38, 1.0194e-38],
        [1.1112e-38, 1.0561e-38, 9.9184e-39, 1.0653e-38, 4.1327e-39, 1.0194e-38]])


In [18]:
x2 = torch.rand(5,4)
print(x2)

tensor([[0.7367, 0.6920, 0.3199, 0.1865],
        [0.9904, 0.3553, 0.8410, 0.7694],
        [0.8908, 0.3722, 0.6244, 0.9159],
        [0.0660, 0.7986, 0.3564, 0.1710],
        [0.5017, 0.0678, 0.5037, 0.4273]])


In [19]:
x3 = torch.zeros(2,4, dtype=torch.long)
print(x3)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])


In [20]:
x4 = torch.tensor([[0.23, 0.45], [1.28, -3.49]])
print(x4)

tensor([[ 0.2300,  0.4500],
        [ 1.2800, -3.4900]])


In [21]:
x2 = x2.new_ones(3,3, dtype=torch.double)
print(x2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [22]:
x2 = torch.randn_like(x2, dtype=torch.float16)
print(x2)

tensor([[-2.6133, -0.7310,  0.3040],
        [-0.6235,  0.7334, -0.5522],
        [ 1.1377, -0.8359, -0.4939]], dtype=torch.float16)


In [23]:
x = x2
y = torch.rand(3, 3, dtype=torch.float16)
print(x + y)
print('\n')
print(torch.add(x, y))

tensor([[-2.5996, -0.6499,  0.7695],
        [-0.2979,  1.3027, -0.3101],
        [ 1.3252, -0.3628,  0.2805]], dtype=torch.float16)


tensor([[-2.5996, -0.6499,  0.7695],
        [-0.2979,  1.3027, -0.3101],
        [ 1.3252, -0.3628,  0.2805]], dtype=torch.float16)


In [24]:
res1 = torch.empty(3, 3, dtype=torch.float16)
torch.mul(x, y, out=res1)
print(res1)

tensor([[-0.0370, -0.0592,  0.1416],
        [-0.2031,  0.4172, -0.1338],
        [ 0.2134, -0.3955, -0.3826]], dtype=torch.float16)


In [25]:
y2 = torch.rand(3,3)
print(y2)
print('\n')
y2.add_(res1)
print(y2)

tensor([[0.3790, 0.9016, 0.3094],
        [0.1261, 0.6167, 0.3363],
        [0.8443, 0.5886, 0.0721]])


tensor([[ 0.3419,  0.8424,  0.4510],
        [-0.0770,  1.0339,  0.2025],
        [ 1.0577,  0.1931, -0.3105]])


In [26]:
print(x3[1,:])

tensor([0, 0, 0, 0])


In [27]:
m = torch.randn(4,4)
n = m.view(16)
p = m.view(-1, 8)
print(m)
print(n)
print(p)

tensor([[ 1.4026,  0.9207,  1.8812,  0.6810],
        [ 0.1470,  1.0684,  0.6833, -1.1697],
        [ 0.8016,  0.8847,  0.3586,  0.3942],
        [ 1.4468, -0.1877,  0.0335, -0.4204]])
tensor([ 1.4026,  0.9207,  1.8812,  0.6810,  0.1470,  1.0684,  0.6833, -1.1697,
         0.8016,  0.8847,  0.3586,  0.3942,  1.4468, -0.1877,  0.0335, -0.4204])
tensor([[ 1.4026,  0.9207,  1.8812,  0.6810,  0.1470,  1.0684,  0.6833, -1.1697],
        [ 0.8016,  0.8847,  0.3586,  0.3942,  1.4468, -0.1877,  0.0335, -0.4204]])


In [28]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [29]:
a.add_(2)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [30]:
import numpy as np
a1 = np.ones(8)
b1 = torch.from_numpy(a1)
np.add(a1, 3, out=a1)
print(a1)

[4. 4. 4. 4. 4. 4. 4. 4.]
